name: Linux build
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04,  ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: install SDL2
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0
    - name: setup SBCL
      run: sudo apt-get install sbcl
    - name: install quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))" --eval "(print ql:*quicklisp-home*)" --eval "(print (user-homedir-pathname))" --quit
    - name: install sketch & harmony & cl-mixed & sketch-fit & stopclock from source
      run: |
        cd $HOME/quicklisp/local-projects/
        git clone https://github.com/Gleefre/stopclock
        git clone https://github.com/Gleefre/sketch-fit
        git clone https://github.com/Gleefre/sketch-buttons
        git clone https://github.com/Gleefre/sketch-utils
        git clone https://github.com/Gleefre/sketch -b define-start-function-2
        git clone https://github.com/Shirakumo/harmony
        git clone https://github.com/Gleefre/cl-mixed
    - name: build
      run: make lin-bundle
    - name: upload release
      uses: actions/upload-artifact@v3
      with:
        name: low-battery-release-${{ matrix.os }}
        path: low-battery-lin.zip
